kind: helm-release
apiVersion: 1.1
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/rarareserve-api
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: rarareserve-api
      tag: $(tag)
      pullPolicy: Never
    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik-azds
      hosts:
      # This expands to form the service's public URL: [space.s.][rootSpace.]rarareserve-api.<random suffix>.<region>.azds.io
      # Customize the public URL by changing the 'rarareserve-api' text between the $(rootSpacePrefix) and $(hostSuffix) tokens
      # For more information see https://aka.ms/devspaces/routing
      - $(spacePrefix)$(rootSpacePrefix)rarareserve-api$(hostSuffix)
configurations:
  develop:
    build:
      useGitIgnore: true
    container:
      sync:
      - "!**/package.json"
      iterate:
        processesToKill: [node]
    install:
      set:
        # 環境変数の設定
        secrets:
          # process.env.DATABASE_URL
          database:
            url: "$DATABASE_URL"
          # process.env.RSA_PRIVATE_KEY
          # process.env.RSA_PUBLIC_KEY
          rsa:
            private:
              key: "$RSA_PRIVATE_KEY"
            public:
              key: "$RSA_PUBLIC_KEY"
          # process.env.SENDGRID_API_KEY
          sendgrid:
            api:
              key: "$SENDGRID_API_KEY"
          # process.env.ENGINE_API_KEY
          engine:
            api:
              key: "$ENGINE_API_KEY"