version: '3.3'
services:
  sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 1433:1433
    restart: always
volumes:
  skidsdb:
    external: true
